### ISSUE TITLE
Suggestion: Link achivement trails to Achivements so completed things do not show.

### ISSUE THREAD

**Issue by Sinaloit** [LadyElyssa/LadyElyssaAchievementGuides#1]
Using the achievementId and achievementBit link specific trails to the relevant achievements so that as each step is completed the trail goes away.

`achievementId - integer. An ID for an achievement from the GW2 API. Markers with the corresponding achievement ID will be hidden if the ID is marked as "done" for the API key that's entered in TacO. For a list of achievement IDs see https://wiki.guildwars2.com/wiki/API:2/achievements`

`achievementBit - integer. This is similar to achievementId, but works for partially completed achievements as well, if the achievement has "bits", they can be individually referenced with this.`

**Comment by LadyElyssa** [comment]
Thank you for the great suggestion and I will look in to adding that in.
