### ISSUE TITLE
Missing lanterns in Amnytas

### ISSUE THREAD

**Issue by Jiendd** [LadyElyssa/LadyElyssaAchievementGuides#3]
Hi! I've been using your markers for a bunch of stuff - first of all, thank you so much! 

However, I noticed that every time I follow them for the "Illuminating Amnytas" completion, I'm like 3 short or something (can't remember exactly) which I then have to wiki to manually find, and they're not on any of the paths. I'm not sure if this has been raised before but I just thought I'd let you know :)

I just did it again to confirm and the 3 missing ones are (based on wiki):

13	Natatorium Obscurus
35	Grand Library of Amnytas
47	Overmere Meditation Circle

Another thing I would add is that it would be nice to have some kind of marker to highlight lantern locations as some of them can be easily missed if not paying extra attention or if the camera is panned in a way that hides it from view while flying/running and the arrow path doesn't look like there's anything there (= it's going pretty much straight). Happened to me a few times, not just on Amnytas for what it's worth. I'm personally not a huge fan of having big icons along the way as they can be a bit obnoxious, but highlighting lanterns by, for example, having the pathing arrows change color for the few feet around the lantern would be a good hint already.

That being said, I am EXTREMELY thankful for all the hard work you do and have done and will obviously keep continue using your markers regardless of whether what I mentioned is changed or not :)

**Comment by LadyElyssa** [comment]
Wow, thank you so much for letting me know and for the valuable feedback, I will look in to those and see what I can do about marker / trail options for those and other lanterns areas.

**Comment by Jiendd** [comment]
Glad I could help! I'll let you know if I find anything else or after trying the new route :)

**Comment by LadyElyssa** [comment]
I have had another look over the SotO Lanterns and found I had managed to walk straight passed one in Skywatch Archipelago, so that's now included and have also added a marker for the lantern locations. Please do let me know if you find it suitable or have any suggestions for it.

I will be going over the lanterns for EoD while I am there adding the map achievements.

**Comment by Jiendd** [comment]
Amazing changes, thank you so much! Finally did a full 3-map run and it was great. Only one tiny little detail I think might be worth adjusting is the arrow pathing for the "Gate Research Lab" lantern at the beginning of part 4 of Skywatch Archipelago, starting from Rata Novus Promenade Waypoint. I followed the shortcut from part 3 which lead me directly to the lab and the camera angle when coming out of the lab if you're panning fairly fast like I do basically meant I missed that one because it's to the side of the arrow path. I only turned around as I was leaving the lab area because I thought "wait, there's 2 lanterns here I'm pretty sure" and as I turned around I saw it right there to the side. :)

It's not a big deal at all and now that I know I won't miss it again, but it might be worth adding a little "detour" to the arrow path coming out of the lab to make sure people don't make that same oopsie I almost did.

Other than that, it is pretty much perfect now! :)

**Comment by LadyElyssa** [comment]
I know the section you mean as I had missed that part myself previously but that path was adjusted in last patch and have noticed this happens occasionally with Blish and need to try and work out when and why so I can let the devs of it know.

I would recommend deleting the pack and then download it again. The path should then show correctly.

Thanks again for your feedback and comments.
